project:
  type: website

website:
  title: "Afonso Matoso Magalhães"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/
      - icon: envelope
        href: mailto:afonsomm98@gmail.com
format:
  html:
    theme: cosmo
    css: styles.css

execute:
  freeze: auto

